services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    networks:
      - incident

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - incident

volumes:
  pgdata:

networks:
  incident:
