#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib.sh
source "${SCRIPT_DIR}/../lib.sh"

require_root
require_systemd

WORKER_HOST="${1:-}"
EXPECTED_FINGERPRINT="${2:-}"
CONTROL_USER="replaybook-control"
WORKER_USER="replaybook"
WORKER_SSH_PORT="${WORKER_SSH_PORT:-22}"
STATE_DIR="/var/lib/replaybook"

[[ -r /etc/replaybook/control.env ]] || die "run controller/bootstrap.sh first"
# This file is generated by controller/bootstrap.sh and owned by root.
# shellcheck source=/dev/null
source /etc/replaybook/control.env

[[ -n "$WORKER_HOST" && -n "$EXPECTED_FINGERPRINT" ]] || \
  die "usage: $0 WORKER_HOST SHA256:FINGERPRINT"
validate_host "$WORKER_HOST"
validate_port "$WORKER_SSH_PORT"
[[ "$EXPECTED_FINGERPRINT" == SHA256:* ]] || die "expected an SHA256 host-key fingerprint"

TMP_KEY="$(mktemp)"
trap 'rm -f "$TMP_KEY"' EXIT
ssh-keyscan -T 10 -p "$WORKER_SSH_PORT" -t ed25519 "$WORKER_HOST" >"$TMP_KEY" 2>/dev/null
[[ -s "$TMP_KEY" ]] || die "could not read the worker's Ed25519 host key"
ACTUAL_FINGERPRINT="$(ssh-keygen -lf "$TMP_KEY" -E sha256 | awk 'NR == 1 { print $2 }')"
[[ "$ACTUAL_FINGERPRINT" == "$EXPECTED_FINGERPRINT" ]] || \
  die "worker fingerprint mismatch: got $ACTUAL_FINGERPRINT"

install -m 0600 -o "$CONTROL_USER" -g "$CONTROL_USER" "$TMP_KEY" "$STATE_DIR/.ssh/known_hosts"

REMOTE_VERSION="$(runuser -u "$CONTROL_USER" -- env HOME="$STATE_DIR" \
  ssh -o BatchMode=yes -o IdentitiesOnly=yes -p "$WORKER_SSH_PORT" \
  "$WORKER_USER@$WORKER_HOST" \
  'replaybook --version')"
LOCAL_VERSION="$(/usr/local/bin/replaybook --version)"
[[ "$REMOTE_VERSION" == "$LOCAL_VERSION" ]] || \
  die "version mismatch: controller is '$LOCAL_VERSION', worker is '$REMOTE_VERSION'"
runuser -u "$CONTROL_USER" -- env HOME="$STATE_DIR" \
  ssh -o BatchMode=yes -o IdentitiesOnly=yes -p "$WORKER_SSH_PORT" \
  "$WORKER_USER@$WORKER_HOST" 'docker compose version'

systemctl restart replaybook-control.service
for _ in {1..20}; do
  if curl --fail --silent --show-error "http://${CONTROL_BIND}/healthz" >/dev/null 2>&1; then
    break
  fi
  sleep 0.25
done
curl --fail --silent --show-error "http://${CONTROL_BIND}/healthz" >/dev/null
systemctl --no-pager --full status replaybook-control.service
echo "Controller and worker are connected; local health check passed."
