services:
  app:
    image: python:3.12-alpine
    command: python -m http.server 3000
    networks:
      - internal

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - internal

networks:
  internal:
